builds:
  - main: main.go
    binary: download-release
    ldflags: -s -w -X main.GitCommit={{.Commit}} -X main.Date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
      - '^tweak'
      - '^test'

brews:
  - tap:
      owner: zcong1993
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/zcong1993/download-release
    description: Easy download github release
    test: |
      system "#{bin}/download-release -h"
